<a href="https://colab.research.google.com/github/srishtiarora42006-hue/Answer/blob/main/Libraries_NumPy_%26_Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1.** Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.

In [27]:
import pandas as pd


df = pd.read_excel("/content/retail_dataset .xlsx")

print('First 5 rows:')
display(df.head())
print('Dataset information:')
display(df.info())

First 5 rows:

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,2023-02-02 00:00:00,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,2024-11-02 00:00:00,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

None

**Q2.** Inspect the dataset and identify missing values in each column. Display the total number of missing
values present in the dataset.

In [10]:
#missing values in each column
missing_values = df.isnull().sum()
print('Missing values in each column:')
print(missing_values)

Missing values in each column:
Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

**Q3.** Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.

In [12]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())

**Q4.** Remove all rows where the Product Category or Region column contains missing values.

In [14]:
df.dropna(subset=["Product Category", "Region"], inplace=True)

**Q5.** Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.

In [15]:
import numpy as np
df["Revenue"] = np.multiply(df["Quantity"], df["Price"])
print('Updated dataset with the new column:')
display(df.head())

Updated dataset with the new column:

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,2023-02-02 00:00:00,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,2024-11-02 00:00:00,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

**Q6.** Using NumPy, calculate the total revenue generated from all transactions in the dataset.

In [16]:
Total_Revenue = np.sum(df["Revenue"])
print('Total revenue generated from all transactions in the dataset:')
print(Total_Revenue)

Total revenue generated from all transactions in the dataset:
465529.66058002145

**Q7.** Group the dataset by Product Category and calculate the total revenue generated by each category.

In [17]:
df.groupby("Product Category")["Revenue"].sum()

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

**Q8.** Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue.

In [18]:
category_revenue = df.groupby("Product Category")["Revenue"].sum()

top_3 = category_revenue.nlargest(3)
bottom_3 = category_revenue.nsmallest(3)

print('Top 3 categories with the highest revenue:')
print(top_3)
print('Bottom 3 categories with the lowest revenue:')
print(bottom_3)

Top 3 categories with the highest revenue:
Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64
Bottom 3 categories with the lowest revenue:
Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

**Q9.** Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue.

In [20]:
region_revenue = df.groupby("Region")["Revenue"].sum()

highest_revenue_region = region_revenue.idxmax()
lowest_revenue_region = region_revenue.idxmin()

print('Region with the highest revenue:')
print(highest_revenue_region)
print('Region with the lowest revenue:')
print(lowest_revenue_region)

Region with the highest revenue:
North
Region with the lowest revenue:
West

**Q10.** Extract the month from the Date column using Pandas and group the dataset by month to calculate the
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
using NumPy.

In [21]:
df["Month"] = pd.to_datetime(df["Date"])
df["Month"] = df["Month"].dt.month

monthly_revenue = df.groupby("Month")["Revenue"].sum()

print('Total monthly revenue:')
print(monthly_revenue)

mean_revenue = np.mean(df["Revenue"])
median_revenue = np.median(df["Revenue"])
std_dev_revenue = np.std(df["Revenue"])

print('Mean revenue:')
print(mean_revenue)
print('Median revenue:')
print(median_revenue)
print('Standard deviation of revenue:')
print(std_dev_revenue)

Total monthly revenue:
Month
1     25439.000000
2     26631.000000
3     13777.000000
4     45871.631579
5     29889.000000
6     39109.000000
7     60252.938776
8     77621.000000
9     36197.210526
10    49961.142857
11    31199.000000
12    29581.736842
Name: Revenue, dtype: float64
Mean revenue:
4900.312216631804
Median revenue:
3282.1052631578946
Standard deviation of revenue:
4721.171795257337